// Code generated by MockGen. DO NOT EDIT.
// Source: golang-postgresql/service (interfaces: AuditLogService)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_service/auditlog.go golang-postgresql/service AuditLogService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	service "golang-postgresql/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogService is a mock of AuditLogService interface.
type MockAuditLogService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogServiceMockRecorder
	isgomock struct{}
}

// MockAuditLogServiceMockRecorder is the mock recorder for MockAuditLogService.
type MockAuditLogServiceMockRecorder struct {
	mock *MockAuditLogService
}

// NewMockAuditLogService creates a new mock instance.
func NewMockAuditLogService(ctrl *gomock.Controller) *MockAuditLogService {
	mock := &MockAuditLogService{ctrl: ctrl}
	mock.recorder = &MockAuditLogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogService) EXPECT() *MockAuditLogServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditLogService) Create(ctx context.Context, req service.CreateAuditLogRequest) (*service.AuditLogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*service.AuditLogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLogService)(nil).Create), ctx, req)
}

// ListByActor mocks base method.
func (m *MockAuditLogService) ListByActor(ctx context.Context, actorID int64, limit int) ([]service.AuditLogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByActor", ctx, actorID, limit)
	ret0, _ := ret[0].([]service.AuditLogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByActor indicates an expected call of ListByActor.
func (mr *MockAuditLogServiceMockRecorder) ListByActor(ctx, actorID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByActor", reflect.TypeOf((*MockAuditLogService)(nil).ListByActor), ctx, actorID, limit)
}
