// Code generated by MockGen. DO NOT EDIT.
// Source: golang-postgresql/repository (interfaces: AuditLogRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/auditlog.go golang-postgresql/repository AuditLogRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "golang-postgresql/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogRepository is a mock of AuditLogRepository interface.
type MockAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditLogRepositoryMockRecorder is the mock recorder for MockAuditLogRepository.
type MockAuditLogRepositoryMockRecorder struct {
	mock *MockAuditLogRepository
}

// NewMockAuditLogRepository creates a new mock instance.
func NewMockAuditLogRepository(ctrl *gomock.Controller) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepository) EXPECT() *MockAuditLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditLogRepository) Create(ctx context.Context, entry repository.AuditLog) (*repository.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entry)
	ret0, _ := ret[0].(*repository.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogRepositoryMockRecorder) Create(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLogRepository)(nil).Create), ctx, entry)
}

// ListByActor mocks base method.
func (m *MockAuditLogRepository) ListByActor(ctx context.Context, params repository.ListByActorParams) ([]repository.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByActor", ctx, params)
	ret0, _ := ret[0].([]repository.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByActor indicates an expected call of ListByActor.
func (mr *MockAuditLogRepositoryMockRecorder) ListByActor(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByActor", reflect.TypeOf((*MockAuditLogRepository)(nil).ListByActor), ctx, params)
}
